### ISSUE TITLE
The plugin `flutter_zoom_plugin` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by nashihu** [umed-jp/umed#1]
I'm using Flutter 2.8.1 and i got this warning when i run `flutter pub get`

```
The plugin `flutter_zoom_plugin` uses a deprecated version of the Android embedding.
           To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
embedding.
           Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
           If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
           https://flutter.dev/go/android-plugin-migration.
```

i'm using this in my pubspec.yaml
```
dependencies:
   flutter_zoom_plugin:
       git:
         url: https://github.com/umed-jp/flutter_zoom_plugin.git
         ref: uzirthapa/134/convertToNullSafety
```
